"""initial schema

Revision ID: 0002_initial_schema
Revises: 0001_extensions
Create Date: 2026-09-15 09:54:37.197983+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_initial_schema"
down_revision: str | None = "0001_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.Text(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "update",
                "delete",
                "read_pd",
                "import",
                "export",
                "login",
                "access_denied",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_action", "audit_log", ["action"], unique=False)
    op.create_index(
        "ix_audit_log_actor_id_occurred_at", "audit_log", ["actor_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_log_entity_type_entity_id",
        "audit_log",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "import_jobs",
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column(
            "target",
            sa.Enum(
                "universities", "it_products", "interactions", "contacts", name="import_target"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "validated", "committed", "failed", "cancelled", name="import_job_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "mapping",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source_headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_index("ix_import_jobs_created_at", "import_jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_import_jobs_deleted_at"), "import_jobs", ["deleted_at"], unique=False)
    op.create_index("ix_import_jobs_file_hash", "import_jobs", ["file_hash"], unique=False)
    op.create_index("ix_import_jobs_status", "import_jobs", ["status"], unique=False)
    op.create_table(
        "import_mapping_presets",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "target",
            sa.Enum(
                "universities", "it_products", "interactions", "contacts", name="import_target"
            ),
            nullable=False,
        ),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_mapping_presets")),
    )
    op.create_index(
        op.f("ix_import_mapping_presets_deleted_at"),
        "import_mapping_presets",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "uq_import_mapping_presets_name_target_live",
        "import_mapping_presets",
        ["name", "target"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "it_directions",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_it_directions")),
    )
    op.create_index(
        op.f("ix_it_directions_deleted_at"), "it_directions", ["deleted_at"], unique=False
    )
    op.create_index(
        "uq_it_directions_name_live",
        "it_directions",
        ["name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_it_directions_name_normalized_live",
        "it_directions",
        ["name_normalized"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "universities",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("inn", sa.Text(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universities")),
    )
    op.create_index(
        op.f("ix_universities_deleted_at"), "universities", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_universities_name_normalized_trgm",
        "universities",
        ["name_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_normalized": "gin_trgm_ops"},
    )
    op.create_index("ix_universities_region", "universities", ["region"], unique=False)
    op.create_index(
        "uq_universities_external_id_live",
        "universities",
        ["external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "uq_universities_name_live",
        "universities",
        ["name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_universities_name_normalized_live",
        "universities",
        ["name_normalized"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "users",
        sa.Column("keycloak_id", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("full_name_normalized", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("role", sa.Enum("user", "manager", "admin", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("keycloak_id", name=op.f("uq_users_keycloak_id")),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(
        "ix_users_full_name_normalized", "users", ["full_name_normalized"], unique=False
    )
    op.create_index(
        "ix_users_full_name_normalized_trgm",
        "users",
        ["full_name_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"full_name_normalized": "gin_trgm_ops"},
    )
    op.create_table(
        "vendors",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_deleted_at"), "vendors", ["deleted_at"], unique=False)
    op.create_index(
        "uq_vendors_name_live",
        "vendors",
        ["name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_vendors_name_normalized_live",
        "vendors",
        ["name_normalized"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "import_rows",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parsed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.Enum("ok", "warning", "error", name="import_row_status"), nullable=False
        ),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_entity_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_jobs.id"],
            name=op.f("fk_import_rows_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_rows")),
        sa.UniqueConstraint("job_id", "row_number", name="uq_import_rows_job_id_row_number"),
    )
    op.create_index(op.f("ix_import_rows_deleted_at"), "import_rows", ["deleted_at"], unique=False)
    op.create_index(
        "ix_import_rows_job_id_status", "import_rows", ["job_id", "status"], unique=False
    )
    op.create_table(
        "it_products",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_it_products_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_it_products")),
    )
    op.create_index(op.f("ix_it_products_deleted_at"), "it_products", ["deleted_at"], unique=False)
    op.create_index(
        "ix_it_products_name_normalized_trgm",
        "it_products",
        ["name_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_normalized": "gin_trgm_ops"},
    )
    op.create_index("ix_it_products_vendor_id", "it_products", ["vendor_id"], unique=False)
    op.create_index(
        "uq_it_products_name_vendor_live",
        "it_products",
        [
            "name_normalized",
            sa.literal_column("COALESCE(vendor_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
        ],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "university_assignments",
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_from", sa.Date(), nullable=False),
        sa.Column("assigned_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.literal_column("university_id"), "="),
            (sa.literal_column("daterange(assigned_from, assigned_to, '[]')"), "&&"),
            where=sa.text("deleted_at IS NULL"),
            using="gist",
            name="university_assignments_no_overlap",
        ),
        sa.CheckConstraint(
            "assigned_to IS NULL OR assigned_to >= assigned_from",
            name=op.f("ck_university_assignments_assignment_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_university_assignments_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_university_assignments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_university_assignments")),
    )
    op.create_index(
        op.f("ix_university_assignments_deleted_at"),
        "university_assignments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_university_assignments_university_id",
        "university_assignments",
        ["university_id"],
        unique=False,
    )
    op.create_index(
        "ix_university_assignments_user_id", "university_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "university_contacts",
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_university_contacts_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_university_contacts")),
    )
    op.create_index(
        op.f("ix_university_contacts_deleted_at"),
        "university_contacts",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_university_contacts_university_id",
        "university_contacts",
        ["university_id"],
        unique=False,
    )
    op.create_index(
        "uq_university_contacts_person_live",
        "university_contacts",
        ["university_id", "full_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "interactions",
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column("it_direction_id", sa.UUID(), nullable=True),
        sa.Column("it_product_id", sa.UUID(), nullable=True),
        sa.Column("responsible_user_id", sa.UUID(), nullable=True),
        sa.Column("contract_number", sa.Text(), nullable=True),
        sa.Column("license_signed_at", sa.Date(), nullable=True),
        sa.Column("license_years", sa.SmallInteger(), nullable=True),
        sa.Column("license_expires_at", sa.Date(), nullable=True),
        sa.Column("transfer_status", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("workflow_version_id", sa.UUID(), nullable=True),
        sa.Column("current_stage_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "license_years IS NULL OR (license_years BETWEEN 1 AND 10)",
            name=op.f("ck_interactions_license_years_range"),
        ),
        sa.ForeignKeyConstraint(
            ["it_direction_id"],
            ["it_directions.id"],
            name=op.f("fk_interactions_it_direction_id_it_directions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["it_product_id"],
            ["it_products.id"],
            name=op.f("fk_interactions_it_product_id_it_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_user_id"],
            ["users.id"],
            name=op.f("fk_interactions_responsible_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_interactions_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interactions")),
    )
    op.create_index(
        op.f("ix_interactions_deleted_at"), "interactions", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_interactions_it_direction_id", "interactions", ["it_direction_id"], unique=False
    )
    op.create_index(
        "ix_interactions_it_product_id", "interactions", ["it_product_id"], unique=False
    )
    op.create_index(
        "ix_interactions_license_expires_at", "interactions", ["license_expires_at"], unique=False
    )
    op.create_index(
        "ix_interactions_license_signed_at", "interactions", ["license_signed_at"], unique=False
    )
    op.create_index(
        "ix_interactions_responsible_user_id", "interactions", ["responsible_user_id"], unique=False
    )
    op.create_index(
        "ix_interactions_university_id", "interactions", ["university_id"], unique=False
    )
    op.create_index(
        "ix_interactions_university_id_it_product_id",
        "interactions",
        ["university_id", "it_product_id"],
        unique=False,
    )
    op.create_index(
        "uq_interactions_business_key_live",
        "interactions",
        [
            "university_id",
            sa.literal_column(
                "COALESCE(it_direction_id, '00000000-0000-0000-0000-000000000000'::uuid)"
            ),
            sa.literal_column(
                "COALESCE(it_product_id, '00000000-0000-0000-0000-000000000000'::uuid)"
            ),
        ],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "it_products_directions",
        sa.Column("it_product_id", sa.UUID(), nullable=False),
        sa.Column("it_direction_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["it_direction_id"],
            ["it_directions.id"],
            name=op.f("fk_it_products_directions_it_direction_id_it_directions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["it_product_id"],
            ["it_products.id"],
            name=op.f("fk_it_products_directions_it_product_id_it_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "it_product_id", "it_direction_id", name=op.f("pk_it_products_directions")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("it_products_directions")
    op.drop_index(
        "uq_interactions_business_key_live",
        table_name="interactions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_interactions_university_id_it_product_id", table_name="interactions")
    op.drop_index("ix_interactions_university_id", table_name="interactions")
    op.drop_index("ix_interactions_responsible_user_id", table_name="interactions")
    op.drop_index("ix_interactions_license_signed_at", table_name="interactions")
    op.drop_index("ix_interactions_license_expires_at", table_name="interactions")
    op.drop_index("ix_interactions_it_product_id", table_name="interactions")
    op.drop_index("ix_interactions_it_direction_id", table_name="interactions")
    op.drop_index(op.f("ix_interactions_deleted_at"), table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(
        "uq_university_contacts_person_live",
        table_name="university_contacts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_university_contacts_university_id", table_name="university_contacts")
    op.drop_index(op.f("ix_university_contacts_deleted_at"), table_name="university_contacts")
    op.drop_table("university_contacts")
    op.drop_index("ix_university_assignments_user_id", table_name="university_assignments")
    op.drop_index("ix_university_assignments_university_id", table_name="university_assignments")
    op.drop_index(op.f("ix_university_assignments_deleted_at"), table_name="university_assignments")
    op.drop_table("university_assignments")
    op.drop_index(
        "uq_it_products_name_vendor_live",
        table_name="it_products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_it_products_vendor_id", table_name="it_products")
    op.drop_index(
        "ix_it_products_name_normalized_trgm",
        table_name="it_products",
        postgresql_using="gin",
        postgresql_ops={"name_normalized": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_it_products_deleted_at"), table_name="it_products")
    op.drop_table("it_products")
    op.drop_index("ix_import_rows_job_id_status", table_name="import_rows")
    op.drop_index(op.f("ix_import_rows_deleted_at"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index(
        "uq_vendors_name_normalized_live",
        table_name="vendors",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_vendors_name_live", table_name="vendors", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_vendors_deleted_at"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(
        "ix_users_full_name_normalized_trgm",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"full_name_normalized": "gin_trgm_ops"},
    )
    op.drop_index("ix_users_full_name_normalized", table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_universities_name_normalized_live",
        table_name="universities",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_universities_name_live",
        table_name="universities",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_universities_external_id_live",
        table_name="universities",
        postgresql_where=sa.text("external_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_universities_region", table_name="universities")
    op.drop_index(
        "ix_universities_name_normalized_trgm",
        table_name="universities",
        postgresql_using="gin",
        postgresql_ops={"name_normalized": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_universities_deleted_at"), table_name="universities")
    op.drop_table("universities")
    op.drop_index(
        "uq_it_directions_name_normalized_live",
        table_name="it_directions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_it_directions_name_live",
        table_name="it_directions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_it_directions_deleted_at"), table_name="it_directions")
    op.drop_table("it_directions")
    op.drop_index(
        "uq_import_mapping_presets_name_target_live",
        table_name="import_mapping_presets",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_import_mapping_presets_deleted_at"), table_name="import_mapping_presets")
    op.drop_table("import_mapping_presets")
    op.drop_index("ix_import_jobs_status", table_name="import_jobs")
    op.drop_index("ix_import_jobs_file_hash", table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_deleted_at"), table_name="import_jobs")
    op.drop_index("ix_import_jobs_created_at", table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity_type_entity_id", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_id_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_action", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###

    # Autogenerate creates the native enum types implicitly but never drops
    # them. Without this block `downgrade base` followed by `upgrade head`
    # fails with "type already exists" — a documented DoD requirement.
    for enum_name in (
        "audit_action",
        "import_job_status",
        "import_row_status",
        "import_target",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
