"""Workflow engine: templates, versions, stages, transitions, history, attachments

Revision ID: 0004_workflow_engine
Revises: 0003_audit_append_only
Create Date: 2026-09-15 14:34:41.258730+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_workflow_engine"
down_revision: str | None = "0003_audit_append_only"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
    )
    op.create_index(op.f("ix_workflows_deleted_at"), "workflows", ["deleted_at"], unique=False)
    op.create_index(
        "uq_workflows_name_normalized_live",
        "workflows",
        ["name_normalized"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_workflows_single_default",
        "workflows",
        [sa.literal_column("(is_default)")],
        unique=True,
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.create_table(
        "workflow_versions",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="workflow_version_status"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_versions_workflow_id_workflows"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint("workflow_id", "version", name="uq_workflow_versions_workflow_version"),
    )
    op.create_index(
        op.f("ix_workflow_versions_deleted_at"), "workflow_versions", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_workflow_versions_workflow_id", "workflow_versions", ["workflow_id"], unique=False
    )
    op.create_index(
        "uq_workflow_versions_single_published",
        "workflow_versions",
        ["workflow_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"),
    )
    op.create_table(
        "workflow_stages",
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_initial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "is_final_success", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_stages_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_stages")),
    )
    op.create_index(
        op.f("ix_workflow_stages_deleted_at"), "workflow_stages", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_workflow_stages_workflow_version_id",
        "workflow_stages",
        ["workflow_version_id"],
        unique=False,
    )
    op.create_index(
        "uq_workflow_stages_code_live",
        "workflow_stages",
        ["workflow_version_id", "code"],
        unique=True,
        postgresql_where=sa.text("code IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "uq_workflow_stages_single_initial",
        "workflow_stages",
        ["workflow_version_id"],
        unique=True,
        postgresql_where=sa.text("is_initial AND deleted_at IS NULL"),
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("from_stage_id", sa.UUID(), nullable=False),
        sa.Column("to_stage_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("requires_comment", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "from_stage_id <> to_stage_id", name=op.f("ck_workflow_transitions_transition_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["from_stage_id"],
            ["workflow_stages.id"],
            name=op.f("fk_workflow_transitions_from_stage_id_workflow_stages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_stage_id"],
            ["workflow_stages.id"],
            name=op.f("fk_workflow_transitions_to_stage_id_workflow_stages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_transitions_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_transitions")),
    )
    op.create_index(
        op.f("ix_workflow_transitions_deleted_at"),
        "workflow_transitions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_transitions_from_stage_id",
        "workflow_transitions",
        ["from_stage_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_transitions_workflow_version_id",
        "workflow_transitions",
        ["workflow_version_id"],
        unique=False,
    )
    op.create_index(
        "uq_workflow_transitions_pair_live",
        "workflow_transitions",
        ["workflow_version_id", "from_stage_id", "to_stage_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "interaction_stage_history",
        sa.Column("interaction_id", sa.UUID(), nullable=False),
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("from_stage_id", sa.UUID(), nullable=True),
        sa.Column("to_stage_id", sa.UUID(), nullable=False),
        sa.Column("transition_id", sa.UUID(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_stage_id"],
            ["workflow_stages.id"],
            name=op.f("fk_interaction_stage_history_from_stage_id_workflow_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("fk_interaction_stage_history_interaction_id_interactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_stage_id"],
            ["workflow_stages.id"],
            name=op.f("fk_interaction_stage_history_to_stage_id_workflow_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["workflow_transitions.id"],
            name=op.f("fk_interaction_stage_history_transition_id_workflow_transitions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_interaction_stage_history_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_interaction_stage_history_workflow_version_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_stage_history")),
    )
    op.create_index(
        "ix_interaction_stage_history_created_at",
        "interaction_stage_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_stage_history_deleted_at"),
        "interaction_stage_history",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_interaction_stage_history_interaction_id",
        "interaction_stage_history",
        ["interaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_interaction_stage_history_to_stage_id",
        "interaction_stage_history",
        ["to_stage_id"],
        unique=False,
    )
    op.create_index(
        "ix_interaction_stage_history_university_id",
        "interaction_stage_history",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "workflow_attachments",
        sa.Column("interaction_id", sa.UUID(), nullable=False),
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column(
            "file_format",
            sa.Enum(
                "png",
                "jpeg",
                "pdf",
                "zip",
                "gzip",
                "rar",
                "doc",
                "docx",
                "xls",
                "xlsx",
                name="attachment_format",
            ),
            nullable=False,
        ),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("fk_workflow_attachments_interaction_id_interactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["workflow_stages.id"],
            name=op.f("fk_workflow_attachments_stage_id_workflow_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_workflow_attachments_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_attachments")),
    )
    op.create_index(
        op.f("ix_workflow_attachments_deleted_at"),
        "workflow_attachments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_attachments_interaction_id",
        "workflow_attachments",
        ["interaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_attachments_stage_id", "workflow_attachments", ["stage_id"], unique=False
    )
    op.create_index(
        "ix_workflow_attachments_university_id",
        "workflow_attachments",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "workflow_attachment_blobs",
        sa.Column("attachment_id", sa.UUID(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["workflow_attachments.id"],
            name=op.f("fk_workflow_attachment_blobs_attachment_id_workflow_attachments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("attachment_id", name=op.f("pk_workflow_attachment_blobs")),
    )
    op.create_index(
        "ix_interactions_current_stage_id", "interactions", ["current_stage_id"], unique=False
    )
    op.create_index(
        "ix_interactions_workflow_version_id", "interactions", ["workflow_version_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_interactions_workflow_version_id_workflow_versions"),
        "interactions",
        "workflow_versions",
        ["workflow_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_interactions_current_stage_id_workflow_stages"),
        "interactions",
        "workflow_stages",
        ["current_stage_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_interactions_current_stage_id_workflow_stages"), "interactions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_interactions_workflow_version_id_workflow_versions"),
        "interactions",
        type_="foreignkey",
    )
    op.drop_index("ix_interactions_workflow_version_id", table_name="interactions")
    op.drop_index("ix_interactions_current_stage_id", table_name="interactions")
    op.drop_table("workflow_attachment_blobs")
    op.drop_index("ix_workflow_attachments_university_id", table_name="workflow_attachments")
    op.drop_index("ix_workflow_attachments_stage_id", table_name="workflow_attachments")
    op.drop_index("ix_workflow_attachments_interaction_id", table_name="workflow_attachments")
    op.drop_index(op.f("ix_workflow_attachments_deleted_at"), table_name="workflow_attachments")
    op.drop_table("workflow_attachments")
    op.drop_index(
        "ix_interaction_stage_history_university_id", table_name="interaction_stage_history"
    )
    op.drop_index(
        "ix_interaction_stage_history_to_stage_id", table_name="interaction_stage_history"
    )
    op.drop_index(
        "ix_interaction_stage_history_interaction_id", table_name="interaction_stage_history"
    )
    op.drop_index(
        op.f("ix_interaction_stage_history_deleted_at"), table_name="interaction_stage_history"
    )
    op.drop_index("ix_interaction_stage_history_created_at", table_name="interaction_stage_history")
    op.drop_table("interaction_stage_history")
    op.drop_index(
        "uq_workflow_transitions_pair_live",
        table_name="workflow_transitions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_workflow_transitions_workflow_version_id", table_name="workflow_transitions")
    op.drop_index("ix_workflow_transitions_from_stage_id", table_name="workflow_transitions")
    op.drop_index(op.f("ix_workflow_transitions_deleted_at"), table_name="workflow_transitions")
    op.drop_table("workflow_transitions")
    op.drop_index(
        "uq_workflow_stages_single_initial",
        table_name="workflow_stages",
        postgresql_where=sa.text("is_initial AND deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_workflow_stages_code_live",
        table_name="workflow_stages",
        postgresql_where=sa.text("code IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_workflow_stages_workflow_version_id", table_name="workflow_stages")
    op.drop_index(op.f("ix_workflow_stages_deleted_at"), table_name="workflow_stages")
    op.drop_table("workflow_stages")
    op.drop_index(
        "uq_workflow_versions_single_published",
        table_name="workflow_versions",
        postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"),
    )
    op.drop_index("ix_workflow_versions_workflow_id", table_name="workflow_versions")
    op.drop_index(op.f("ix_workflow_versions_deleted_at"), table_name="workflow_versions")
    op.drop_table("workflow_versions")
    op.drop_index(
        "uq_workflows_single_default",
        table_name="workflows",
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_workflows_name_normalized_live",
        table_name="workflows",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_workflows_deleted_at"), table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###

    # Autogenerate creates the native enum types implicitly but never drops
    # them; without this `downgrade base` then `upgrade head` fails.
    for enum_name in ("attachment_format", "workflow_version_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
