"""Integration sync runs: one row per synchronisation attempt

Revision ID: 0005_integration_syncs
Revises: 0004_workflow_engine
Create Date: 2026-09-17 11:13:18.002192+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005_integration_syncs"
down_revision: str | None = "0004_workflow_engine"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_sync_runs",
        sa.Column("source", sa.Enum("lms", "website", name="integration_source"), nullable=False),
        sa.Column("mode", sa.Enum("fixture", "http", name="integration_mode"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "succeeded", "failed", name="integration_sync_status"),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_sync_runs")),
    )
    op.create_index(
        op.f("ix_integration_sync_runs_deleted_at"),
        "integration_sync_runs",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_integration_sync_runs_source_created_at",
        "integration_sync_runs",
        ["source", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_integration_sync_runs_status", "integration_sync_runs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_integration_sync_runs_status", table_name="integration_sync_runs")
    op.drop_index("ix_integration_sync_runs_source_created_at", table_name="integration_sync_runs")
    op.drop_index(op.f("ix_integration_sync_runs_deleted_at"), table_name="integration_sync_runs")
    op.drop_table("integration_sync_runs")
    # ### end Alembic commands ###

    # Autogenerate creates the native enum types implicitly but never drops them.
    for enum_name in ("integration_sync_status", "integration_mode", "integration_source"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
